# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false

os:
  - linux
  - osx

julia:
  - 1.0

notifications:
  email: false

git:
  depth: 99999999

addons:
  homebrew:
    packages:
    - telnet
    update: true

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
# matrix:
#  allow_failures:
#  - julia: nightly

after_success:
  - julia -e 'using Pkg'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("HORIZONS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("HORIZONS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
